# Generated by Django 4.1.4 on 2023-04-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='s_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
