# Generated by Django 4.1.4 on 2023-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_leave_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
