# Generated by Django 4.1.4 on 2023-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_leave_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
