# Generated by Django 4.1.4 on 2023-04-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_leave_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='visitor_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
