# Generated by Django 4.1.4 on 2023-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_visitors_visitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
