# Generated by Django 4.1.4 on 2023-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_warden_gatepass_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='gatepass_generated',
        ),
        migrations.AddField(
            model_name='leave',
            name='gatepass_generated',
            field=models.BooleanField(default=False),
        ),
    ]
